[book]
title = "Rael I"
authors = ["Rael"]
description = "Web book of Rael's first publication."
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/wheelofheaven/rael-one-the-book-which-tells-the-truth"
git-repository-icon = "fa-github"

